// <auto-generated />
using Api_Vendas.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Api_Vendas.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230730030920_FirstMigration")]
    partial class FirstMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Api_Vendas.Models.Item", b =>
                {
                    b.Property<string>("CodItem")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("NameItem")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("CodItem");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("Api_Vendas.Models.ItemSale", b =>
                {
                    b.Property<string>("CodItem")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("IdSale")
                        .HasColumnType("int");

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.HasKey("CodItem", "IdSale");

                    b.HasIndex("IdSale");

                    b.ToTable("ItemSale");
                });

            modelBuilder.Entity("Api_Vendas.Models.Sale", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.ToTable("Sales");
                });

            modelBuilder.Entity("Api_Vendas.Models.ItemSale", b =>
                {
                    b.HasOne("Api_Vendas.Models.Item", "Item")
                        .WithMany("Sales")
                        .HasForeignKey("CodItem")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Api_Vendas.Models.Sale", "Sale")
                        .WithMany("Items")
                        .HasForeignKey("IdSale")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("Sale");
                });

            modelBuilder.Entity("Api_Vendas.Models.Item", b =>
                {
                    b.Navigation("Sales");
                });

            modelBuilder.Entity("Api_Vendas.Models.Sale", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
